---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: 754450290666.dkr.ecr.us-east-1.amazonaws.com/my-app/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "http://java-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: 754450290666.dkr.ecr.us-east-1.amazonaws.com/my-app/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "qa"
        - name: CLIENT_URL
          value: "http://angular-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer